DROP TABLE IF EXISTS patients_tbl;
DROP TABLE IF EXISTS doctors_tbl;
DROP TABLE IF EXISTS recipes_tbl;
DROP TABLE IF EXISTS priorityOfRecipe_tbl;

CREATE TABLE patients_tbl(
    patient_id BIGINT NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    firstName_fld VARCHAR(45) NOT NULL,
    lastName_fld VARCHAR(45) NOT NULL ,
    patronymic_fld VARCHAR(45) NOT NULL,
    phoneNumber_fld VARCHAR(11) UNIQUE
);

CREATE TABLE doctors_tbl(
    doctor_id BIGINT NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    firstName_fld VARCHAR(45) NOT NULL,
    lastName_fld VARCHAR(45) NOT NULL ,
    patronymic_fld VARCHAR(45) NOT NULL,
    specialization_fld VARCHAR(55) NOT NULL
);

CREATE TABLE priorityOfRecipe_tbl(
    priority_id BIGINT NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    priorityName_fld VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE recipes_tbl(
    recipe_id BIGINT NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    description_fld VARCHAR(800) NOT NULL,
    patient_id_fld BIGINT NOT NULL ,
    doctor_id_fld BIGINT NOT NULL ,
    creationDate_fld DATE NOT NULL ,
    priority_id_fld BIGINT NOT NULL ,

    CONSTRAINT recipe_patient_fk FOREIGN KEY (patient_id_fld) REFERENCES patients_tbl (patient_id) ON DELETE RESTRICT ,
    CONSTRAINT recipe_doctor_fk FOREIGN KEY (doctor_id_fld) REFERENCES doctors_tbl (doctor_id) ON DELETE RESTRICT ,
    CONSTRAINT recipe_priority_fk FOREIGN KEY (priority_id_fld) REFERENCES priorityOfRecipe_tbl (priority_id) ON DELETE RESTRICT
);


INSERT INTO patients_tbl (firstName_fld, lastName_fld, patronymic_fld, phoneNumber_fld)
    VALUES ('Иванов', 'Иван', 'Иванович', 89998889876),
           ('Николаев', 'Николай', 'Николаевич', 89997776543);

INSERT INTO doctors_tbl (firstName_fld, lastName_fld, patronymic_fld, specialization_fld)
    VALUES ('Петров', 'Андрей', 'Андреевич', 'Терапевт'),
        ('Андреев', 'Петр', 'Петрович', 'Хирург') ;

INSERT INTO priorityOfRecipe_tbl (priorityName_fld)
    VALUES ('Нормальный'), ('Срочный'), ('Немедленный');

INSERT INTO recipes_tbl(description_fld, patient_id_fld, doctor_id_fld,
                        creationDate_fld, priority_id_fld)
    VALUES ('Препарат от простуды', 1, 1, '2020-01-01', 1),
           ('Препарат для укрепления суставов', 2, 2, '2020-08-31', 2),
           ('Препарат для восстановления костей', 1, 2, '2020-08-31', 3);